{
 "title": "Actor System Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Actors active",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(DispatcherActor_started_total - DispatcherActor_terminated_total) or DispatcherActor_started_total",
     "legendFormat": "DispatcherActor active"
    },
    {
     "expr": "(ProcessingActor_started_total - ProcessingActor_terminated_total) or ProcessingActor_started_total",
     "legendFormat": "ProcessingActors active"
    },
    {
     "expr": "((DispatcherActor_started_total - DispatcherActor_terminated_total) or DispatcherActor_started_total) + ((ProcessingActor_started_total - ProcessingActor_terminated_total) or ProcessingActor_started_total)",
     "legendFormat": "Actors Count Total"
    }
   ]
  },
  {
   "title": "Deadletter Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    { "expr": "DeadLetter_Count_total{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Dequeue Actor Ask Max Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "actorsystem_ask_time_seconds_max",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}