{
 "title": "Sensor Data Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Sensor Value max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"sensordata\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n      r._measurement == \"aggregate\"\r\n  )\r\n  |> filter(fn: (r) => r[\"_field\"] == \"max\")\r\n\r\n  "
    }
   ]
  },
  {
   "title": "Sensor Value min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"sensordata\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n      r._measurement == \"aggregate\"\r\n  )\r\n  |> filter(fn: (r) => r[\"_field\"] == \"min\")\r\n\r\n  "
    }
   ]
  },
  {
   "title": "Sensor Value median",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"sensordata\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n      r._measurement == \"aggregate\"\r\n  )\r\n  |> filter(fn: (r) => r[\"_field\"] == \"median\")\r\n\r\n  "
    }
   ]
  },
  {
   "title": "Sensor Value avg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"sensordata\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n      r._measurement == \"aggregate\"\r\n  )\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mean\")\r\n\r\n  "
    }
   ]
  },
  {
   "title": "Sensor Value standard deviation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"sensordata\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n      r._measurement == \"aggregate\"\r\n  )\r\n  |> filter(fn: (r) => r[\"_field\"] == \"standardDeviation\")\r\n\r\n  "
    }
   ]
  },
  {
   "title": "Sensor Value standard p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"sensordata\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n      r._measurement == \"aggregate\"\r\n  )\r\n  |> filter(fn: (r) => r[\"_field\"] == \"p95\")\r\n\r\n  "
    }
   ]
  }
 ]
}