global:
  scrape_interval: 20s
  evaluation_interval: 20s

scrape_configs:
  - job_name: iot-processor-metrics
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8080"]
  - job_name: iot-rabbitmq-metrics
    metrics_path: /metrics
    static_configs:
      - targets: ["rabbitmq:15692"]
  - job_name: iot-processor-cadvisor-metrics
    static_configs:
      - targets: ["cadvisor:7070", "node-exporter:9100"]
