### general config
spring:
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false
  iotProcessor:
    influxdb:
      url: ${influxUrl}
      username: ${influxUsername}
      password: ${influxPassword}
      bucket: ${influxBucket:sensordata}
      org: ${influxOrg:iot-processor}
      token: ${influxToken}
logging:
  level:
    root: info
akka:
  conf: application.conf
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
---
### dev specific config
spring:
  config:
    activate:
      on-profile: dev

---
### prod specific config
spring:
  config:
    activate:
      on-profile: prod