version: "3"
services:
  backend:
    image: iot-processor:latest
    container_name: backend
    build:
      context: ../backend
      dockerfile: Dockerfile
    environment:
      influxPassword: password1234
      influxToken: c54a64aa5d5e9f2b1c6e351b3f2c984b25400235df85ea431b8219c92551f5dd
      influxUrl: http://localhost:8086
      influxUsername: admin
      rabbitmqPassword: password1234
      rabbitmqUsername: admin
      rabbitmqHost: rabbitmq
    depends_on:
      - rabbitmq
    ports:
      - 8080:8080

  testdata-generator:
    container_name: testdata-generator
    build:
      context: ../test-data-generator
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  node-exporter:
    image: prom/node-exporter:latest
    container_name: nodeExporter
    restart: unless-stopped
    expose:
      - 9100

  cadvisor:
    image: google/cadvisor:latest
    container_name: cAdvisor
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    expose:
      - 7070
    command:
      - "-port=7070"

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    volumes:
      #  - rabbitmq-storage:/var/lib/rabbitmq
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
      - ./rabbitmq/plugins:/etc/rabbitmq/enabled_plugins"

    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    extra_hosts:
      - host.docker.internal:host-gateway

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    #  - prometheus-storage:/prometheus
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
    restart: always
    ports:
      - 9090:9090
    extra_hosts:
      - host.docker.internal:host-gateway
    expose:
      - 9090
    links:
      - cadvisor:cadvisor
      - node-exporter:node-exporter

  influxdb:
    container_name: influxdb
    image: influxdb:latest
    volumes:
      - /var/lib/influxdb2
      - ./influxdb/scripts:/docker-entrypoint-initdb.d
    env_file:
      - .env
    restart: on-failure:10
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT}:8086

  telegraf:
    container_name: telegraf
    image: telegraf:latest
    volumes:
      - ${TELEGRAF_CFG_PATH}:/etc/telegraf/telegraf.conf:rw
    env_file:
      - .env
    depends_on:
      - influxdb

  grafana:
    container_name: grafana
    image: grafana/grafana
    volumes:
      #   - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password1234
    ports:
      - 3000:3000
    depends_on:
      - influxdb
#volumes:
# influxdb-storage: {}
# prometheus-storage: {}
# grafana-storage: {}
