global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: iot-processor-metrics
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8080"]
  - job_name: iot-rabbitmq-metrics
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:15692"]
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
          [
            "localhost:9090",
            "cadvisor:7070",
            "node-exporter:9100",
            "nginx-exporter:9113",
          ]
