global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: iot-processor-metrics
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8080"]
#  - job_name: iot-processor-metrics-kamon
#    metrics_path: /metrics
#    static_configs:
#      - targets: ["host.docker.internal:9095"]
